// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czevtnxzdaxgkjvqeogf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZXZ0bnh6ZGF4Z2tqdnFlb2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODY5NzksImV4cCI6MjA2MjQ2Mjk3OX0.b1B_oJtSyfFmS2jv7v2w8FjdFNFkcR2J3-JSmGeanCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);